export const diccionario = {
  es: [
    { key: "Perfil", value: "Perfil" },
    { key: "Inicio", value: "Inicio" },
    { key: "Mis Viajes", value: "Mis Viajes" },
    { key: "Pagos", value: "Pagos" },
    { key: "Configuración", value: "Configuración" },
    { key: "Guardar tarjeta", value: "Guardar tarjeta" },
    { key: "Hora", value: "Hora" },
    { key: "Platform Management", value: "Gestión de la Plataforma" },
    { key: "usuarios", value: "Usuarios" },
    { key: "conductores", value: "Conductores" },
    { key: "pasajeros", value: "Pasajeros" },
    { key: "vehiculos", value: "Vehículos" },
    { key: "vehiculo", value: "Vehículo" },
    { key: "viajes", value: "Viajes" },
    { key: "Correo Electrónico", value: "Correo Electrónico" },
    {
      key: "Buscar vehículo por patente o marca...",
      value: "Buscar vehículo por patente o marca...",
    },
    {
      key: "Buscar viaje por fecha u origen...",
      value: "Buscar viaje por fecha u origen...",
    },
    {
      key: "Buscar usuario por N° documento o nombre...",
      value: "Buscar usuario por N° documento o nombre...",
    },
    { key: "Cerrar", value: "Cerrar" },
    { key: "Agregar", value: "Agregar" },
    { key: "Agregar Usuario", value: "Agregar Usuario" },
    { key: "Agregar Conductor", value: "Agregar Conductor" },
    { key: "Agregar Vehículo", value: "Agregar Vehículo" },
    { key: "Guardar", value: "Guardar" },
    { key: "Activo", value: "Activo" },
    { key: "Inactivo", value: "Inactivo" },
    { key: "Cancelado", value: "Cancelado" },
    { key: "N/A", value: "N/A" },
    { key: "Completado", value: "Completado" },
    { key: "Pendiente", value: "Pendiente" },
    { key: "Editar", value: "Editar" },
    { key: "id", value: "ID" },
    { key: "Nombre", value: "Nombre" },
    { key: "DNI", value: "DNI" },
    { key: "Email", value: "Email" },
    { key: "N° de Viaje", value: "N° de Viaje" },
    { key: "Dirección", value: "Dirección" },
    { key: "Estado", value: "Estado" },
    { key: "Acciones", value: "Acciones" },
    { key: "Fecha registro", value: "Fecha registro" },
    { key: "Patente", value: "Patente" },
    { key: "Marca", value: "Marca" },
    { key: "Modelo", value: "Modelo" },
    { key: "Año", value: "Año" },
    { key: "Color", value: "Color" },
    { key: "Conductor", value: "Conductor" },
    { key: "Fecha", value: "Fecha" },
    { key: "Origen", value: "Origen" },
    { key: "Destino", value: "Destino" },
    { key: "Pasajero", value: "Pasajero" },
    { key: "Importe", value: "Importe" },
    { key: "Resumen", value: "Resumen" },
    { key: "Editar", value: "Editar" },
    { key: "Guardar Cambios", value: "Guardar Cambios" },
    { key: "Ingrese el conductor", value: "Ingrese el conductor" },
    { key: "Ingrese el año", value: "Ingrese el año" },
    { key: "Ingrese el color", value: "Ingrese el color" },
    { key: "Ingrese la patente", value: "Ingrese la patente" },
    { key: "Ingrese el modelo", value: "Ingrese el modelo" },
    { key: "Ingrese la marca", value: "Ingrese la marca" },
    { key: "Ingrese su nombre", value: "Ingrese su nombre" },
    { key: "Ingrese su DNI", value: "Ingrese su DNI" },
    {
      key: "Ingrese su correo electrónico",
      value: "Ingrese su correo electrónico",
    },
    { key: "Ingrese su contraseña", value: "Ingrese su contraseña" },
    { key: "Masculino", value: "Masculino" },
    { key: "Femenino", value: "Femenino" },
    { key: "Otro", value: "Otro" },
    { key: "Género", value: "Género" },
    { key: "Actualizado", value: "Actualizado" },
    { key: "Ultima actualización", value: "Ultima actualización" },
    { key: "Ubicación actual", value: "Ubicación actual" },
    { key: "Ver ruta", value: "Ver ruta" },
    {
      key: "Buscar por patente o conductor",
      value: "Buscar por patente o conductor",
    },
    { key: "Contraseña Actual", value: "Contraseña Actual" },
    { key: "Nueva Contraseña", value: "Nueva Contraseña" },
    {
      key: "Gestiona la seguridad de tu cuenta",
      value: "Gestiona la seguridad de tu cuenta",
    },
    { key: "Actualizar Contraseña", value: "Actualizar Contraseña" },
    { key: "Seguridad", value: "Seguridad" },
    { key: "Confirmar Contraseña", value: "Confirmar Contraseña" },
    { key: "Selecciona tu género", value: "Selecciona tu género" },
    { key: "Información Personal", value: "Información Personal" },
    {
      key: "Actualiza tu información de perfil",
      value: "Actualiza tu información de perfil",
    },
    { key: "Apariencia", value: "Apariencia" },
    {
      key: "Personaliza la apariencia de la aplicación",
      value: "Personaliza la apariencia de la aplicación",
    },
    { key: "Modo Oscuro", value: "Modo Oscuro" },
    { key: "Modo Claro", value: "Modo Claro" },
    {
      key: "Cambia entre modo claro y oscuro",
      value: "Cambia entre modo claro y oscuro",
    },
    { key: "Idioma", value: "Idioma" },
    { key: "Español", value: "Español" },
    { key: "English", value: "Inglés " },
    { key: "Notificaciones", value: "Notificaciones" },
    {
      key: "Configura cómo quieres recibir notificaciones",
      value: "Configura cómo quieres recibir notificaciones",
    },
    { key: "Notificaciones Push", value: "Notificaciones Push" },
    {
      key: "Recibe notificaciones en tu dispositivo",
      value: "Recibe notificaciones en tu dispositivo",
    },
    { key: "Sonidos", value: "Sonidos" },
    {
      key: "Reproduce sonidos para notificaciones importantes",
      value: "Reproduce sonidos para notificaciones importantes",
    },
    { key: "Correos Electrónicos", value: "Correos Electrónicos" },
    {
      key: "Recibe actualizaciones por correo electrónico",
      value: "Recibe actualizaciones por correo electrónico",
    },
    { key: "Privacidad y Seguridad", value: "Privacidad y Seguridad" },
    {
      key: "Gestiona la privacidad y seguridad de tu cuenta",
      value: "Gestiona la privacidad y seguridad de tu cuenta",
    },
    {
      key: "Autenticación de dos factores",
      value: "Autenticación de dos factores",
    },
    {
      key: "Añade una capa extra de seguridad a tu cuenta",
      value: "Añade una capa extra de seguridad a tu cuenta",
    },
    {
      key: "Compartir datos de ubicación",
      value: "Compartir datos de ubicación",
    },
    {
      key: "Permite que la app acceda a tu ubicación",
      value: "Permite que la app acceda a tu ubicación",
    },
    { key: "Historial de sesiones", value: "Historial de sesiones" },
    {
      key: "Ver y gestionar tus sesiones activas",
      value: "Ver y gestionar tus sesiones activas",
    },
    { key: "Información Legal", value: "Información Legal" },
    {
      key: "Términos y condiciones de uso",
      value: "Términos y condiciones de uso",
    },
    { key: "Términos de Servicio", value: "Términos de Servicio" },
    { key: "Ver", value: "Ver" },
    { key: "Política de Privacidad", value: "Política de Privacidad" },
    { key: "Licencias de Terceros", value: "Licencias de Terceros" },
    { key: "Cerrar Sesión", value: "Cerrar Sesión" },
    { key: "Eliminar Cuenta", value: "Eliminar Cuenta" },
    { key: "Panel del Conductor", value: "Panel del Conductor" },
    { key: "Efectivo", value: "Efectivo" },
    { key: "Conectado", value: "Conectado" },
    { key: "Desconectado", value: "Desconectado" },
    { key: "Recoger en", value: "Recoger en" },
    { key: "Destino", value: "Destino" },
    { key: "Rechazar", value: "Rechazar" },
    { key: "Aceptar", value: "Aceptar" },
    { key: "Viaje", value: "Viaje" },
    { key: "Ganancias", value: "Ganancias" },
    { key: "Distancia", value: "Distancia" },
    { key: "Tiempo", value: "Tiempo" },
    { key: "Mensajes", value: "Mensajes" },
    { key: "Salir", value: "Salir" },
    { key: "Ruta", value: "Ruta" },
    { key: "Duración", value: "Duración" },
    { key: "Todos", value: "Todos" },
    {
      key: "Buscar por dirección o fecha",
      value: "Buscar por dirección o fecha",
    },
    { key: "Distancia total", value: "Distancia total" },
    { key: "Ingresos totales", value: "Ingresos totales" },
    { key: "Total de viajes", value: "Total de viajes" },
    { key: "Ver detalles", value: "Ver detalles" },
    { key: "Descargar Reporte", value: "Descargar Reporte" },
    { key: "Buscar", value: "Buscar" },
    { key: "Mis vehiculos", value: "Mis vehículos" },
    { key: "Editar vehículo", value: "Editar vehículo" },
    { key: "Revisión", value: "Revisión" },
    { key: "Agregar Nuevo Vehículo", value: "Agregar Nuevo Vehículo" },
    { key: "Cancelar", value: "Cancelar" },
    { key: "¿A dónde quieres ir hoy?", value: "¿A dónde quieres ir hoy?" },
    { key: "¿A dónde vas?", value: "¿A dónde vas?" },
    { key: "Mi ubicación actual", value: "Mi ubicación actual" },
    { key: "Solicitar Taxi", value: "Solicitar Taxi" },
    { key: "Viajes Recientes", value: "Viajes Recientes" },
    { key: "Ver todos los viajes", value: "Ver todos los viajes" },
    { key: "Viaje programado", value: "Viaje programado" },
    {
      key: "Programa un viaje para más tarde",
      value: "Programa un viaje para más tarde",
    },
    { key: "Favoritos", value: "Favoritos" },
    { key: "Tus destinos favoritos", value: "Tus destinos favoritos" },
    { key: "Métodos de Pago", value: "Métodos de Pago" },
    {
      key: "Gestiona tus métodos de pago",
      value: "Gestiona tus métodos de pago",
    },
    { key: "Agregar", value: "Agregar" },
    {
      key: "Añadir nuevo destino o preferencia",
      value: "Añadir nuevo destino o preferencia",
    },
    { key: "Hola", value: "Hola" },
    { key: "Tarjeta", value: "Tarjeta" },
    { key: "Seleccione su vehículo", value: "Seleccione su vehículo" },
    {
      key: "Elige el tipo de coche para tu viaje",
      value: "Elige el tipo de coche para tu viaje",
    },
    { key: "pasajeros", value: "pasajeros" },
    { key: "Llegada", value: "Llegada" },
    { key: "Efectivo", value: "Efectivo" },
    { key: "Pagarás", value: "Pagarás" },
    { key: "final del viaje", value: "final del viaje" },
    { key: "Pedir Ahora", value: "Pedir Ahora" },
    { key: "en efectivo", value: "en efectivo" },
    { key: "con tarjeta", value: "con tarjeta" },
    { key: "Buscando un taxi cercano", value: "Buscando un taxi cercano" },
    { key: "Esto tomará unos segundos", value: "Esto tomará unos segundos" },
    { key: "¡Tu taxi está en camino!", value: "¡Tu taxi está en camino!" },
    { key: "¡Taxi en camino!", value: "¡Taxi en camino!" },
    {
      key: "Tu conductor llegará en aproximadamente 3 minutos",
      value: "Tu conductor llegará en aproximadamente 3 minutos",
    },
    { key: "Contactar", value: "Contactar" },
    { key: "Llegada estimada", value: "Llegada estimada" },
    { key: "Buscar viajes", value: "Buscar viajes" },
    { key: "Programar Viaje", value: "Programar Viaje" },
    { key: "Programado", value: "Programado" },
    { key: "Tu próximo viaje", value: "Tu próximo viaje" },
    { key: "Tu próximo viaje", value: "Your next trip" },
    { key: "Programar Nuevo Viaje", value: "Programar Nuevo Viaje" },
    { key: "Fecha", value: "Fecha" },
    { key: "Hora", value: "Hora" },
    { key: "Programar", value: "Programar" },
    { key: "Editar Viaje", value: "Editar Viaje" },
    { key: "Métodos de Pago Guardados", value: "Métodos de Pago Guardados" },
    {
      key: "Selecciona tu método de pago predeterminado",
      value: "Selecciona tu método de pago predeterminado",
    },
    { key: "Agregar método de pago", value: "Agregar método de pago" },
    { key: "Historial de Pagos", value: "Historial de Pagos" },
    { key: "Revisa tus pagos recientes", value: "Revisa tus pagos recientes" },
    { key: "Ver historial completo", value: "Ver historial completo" },
    { key: "Detalles de viaje", value: "Detalles de viaje" },
    { key: "Fecha y Hora", value: "Fecha y Hora" },
    { key: "Ubicaciones", value: "Ubicaciones" },
    { key: "Total", value: "Total" },
    { key: "Origen", value: "Origen" },
    { key: "Método de Pago", value: "Método de Pago" },
    {
      key: "Historial Completo de Viajes",
      value: "Historial Completo de Viajes",
    },
    { key: "Añadir Nueva Tarjeta", value: "Añadir Nueva Tarjeta" },
    {
      key: "Ingresa los detalles de tu tarjeta",
      value: "Ingresa los detalles de tu tarjeta",
    },
    { key: "Número de Tarjeta", value: "Número de Tarjeta" },
    { key: "Fecha de Expiración", value: "Fecha de Expiración" },
    { key: "Nombre en la Tarjeta", value: "Nombre en la Tarjeta" },
    { key: "País", value: "País" },
    { key: "Selecciona un país", value: "Selecciona un país" },
    { key: "Guardar un país", value: "Guardar un país" },
    { key: "Nombre completo", value: "Nombre completo" },
    {
      key: "Por favor completa todos los campos",
      value: "Por favor completa todos los campos",
    },
    { key: "Número de tarjeta inválido", value: "Número de tarjeta inválido" },
    {
      key: "¿Confirmar programación del viaje?",
      value: "¿Confirmar programación del viaje?",
    },
    { key: "Confirmar", value: "Confirmar" },
    {
      key: "¿Estás seguro de cancelar el viaje?",
      value: "¿Estás seguro de cancelar el viaje?",
    },
  ],
  en: [
    { key: "Perfil", value: "Profile" },
    { key: "Inicio", value: "Home" },
    { key: "Mis Viajes", value: "My Trips" },
    { key: "Pagos", value: "Payments" },
    { key: "Configuración", value: "Settings" },
    {
      key: "¿Estás seguro de cancelar el viaje?",
      value: "Are you sure you want to cancel the trip?",
    },
    { key: "Confirmar", value: "Confirm" },
    {
      key: "¿Confirmar programación del viaje?",
      value: "Confirm trip booking?",
    },
    {
      key: "Por favor completa todos los campos",
      value: "Please fill out all fields",
    },
    { key: "Hora", value: "Time" },
    { key: "Número de tarjeta inválido", value: "Invalid card number" },
    { key: "Guardar tarjeta", value: "Save Card" },
    { key: "Nombre completo", value: "Full Name" },
    { key: "Añadir Nueva Tarjeta", value: "Add New Card" },
    {
      key: "Ingresa los detalles de tu tarjeta",
      value: "Enter your card details",
    },
    { key: "Número de Tarjeta", value: "Card Number" },
    { key: "Fecha de Expiración", value: "Expiration Date" },
    { key: "Nombre en la Tarjeta", value: "Name on Card" },
    { key: "País", value: "Country" },
    { key: "Selecciona un país", value: "Select a country" },
    { key: "Guardar un país", value: "Save a country" },
    { key: "Historial Completo de Viajes", value: "Full Trip History" },
    { key: "Cerrar", value: "Close" },
    { key: "Origen", value: "Origin" },
    { key: "Total", value: "Total" },
    { key: "Programar Nuevo Viaje", value: "Schedule New Trip" },
    { key: "Fecha", value: "Date" },
    { key: "Hora", value: "Time" },
    { key: "Programar", value: "Schedule" },
    { key: "Programado", value: "Scheduled" },
    { key: "Buscar viajes", value: "Search trips" },
    { key: "Programar Viaje", value: "Schedule Trip" },
    { key: "¡Taxi en camino!", value: "Taxi on the way!" },
    {
      key: "Tu conductor llegará en aproximadamente 3 minutos",
      value: "Your driver will arrive in approximately 3 minutes",
    },
    { key: "Contactar", value: "Contact" },
    { key: "Llegada estimada", value: "Estimated arrival" },
    { key: "¡Tu taxi está en camino!", value: "Your taxi is on the way!" },
    { key: "Buscando un taxi cercano", value: "Looking for a nearby taxi" },
    { key: "Esto tomará unos segundos", value: "This will take a few seconds" },
    { key: "Tarjeta", value: "Card" },
    { key: "Seleccione su vehículo", value: "Select your vehicle" },
    {
      key: "Elige el tipo de coche para tu viaje",
      value: "Choose the type of car for your trip",
    },
    { key: "pasajeros", value: "passengers" },
    { key: "Llegada", value: "Arrival" },
    { key: "Efectivo", value: "Cash" },
    { key: "Pagarás", value: "You will pay" },
    { key: "final del viaje", value: "at the end of the trip" },
    { key: "Pedir Ahora", value: "Request Now" },
    { key: "en efectivo", value: "in cash" },
    { key: "con tarjeta", value: "by card" },
    { key: "Hola", value: "Hello" },
    {
      key: "¿A dónde quieres ir hoy?",
      value: "Where do you want to go today?",
    },
    { key: "¿A dónde vas?", value: "Where are you going?" },
    { key: "Mi ubicación actual", value: "My current location" },
    { key: "Solicitar Taxi", value: "Request Taxi" },
    { key: "Viajes Recientes", value: "Recent Trips" },
    { key: "Ver todos los viajes", value: "View All Trips" },
    { key: "Viaje programado", value: "Scheduled Trip" },
    {
      key: "Programa un viaje para más tarde",
      value: "Schedule a trip for later",
    },
    { key: "Favoritos", value: "Favorites" },
    { key: "Tus destinos favoritos", value: "Your favorite destinations" },
    { key: "Métodos de Pago", value: "Payment Methods" },
    {
      key: "Gestiona tus métodos de pago",
      value: "Manage your payment methods",
    },
    { key: "Agregar", value: "Add" },
    {
      key: "Añadir nuevo destino o preferencia",
      value: "Add new destination or preference",
    },
    { key: "Cancelar", value: "Cancel" },
    { key: "Agregar Nuevo Vehículo", value: "Add New Vehicle" },
    { key: "Revisión", value: "Inspection" },
    { key: "Buscar", value: "Search" },
    { key: "Apariencia", value: "Appearance" },
    { key: "N° de Viaje", value: "Trip N°" },
    {
      key: "Personaliza la apariencia de la aplicación",
      value: "Customize the app appearance",
    },
    { key: "Modo Oscuro", value: "Dark Mode" },
    { key: "Modo Claro", value: "Light Mode" },
    {
      key: "Cambia entre modo claro y oscuro",
      value: "Toggle between light and dark mode",
    },
    { key: "Idioma", value: "Language" },
    { key: "Español", value: "Spanish" },
    { key: "English", value: "English" },
    { key: "Ultima actualización", value: "Last update" },
    { key: "Ubicación actual", value: "Current location" },
    { key: "Ver ruta", value: "View route" },
    { key: "Ruta", value: "Route" },
    { key: "Duración", value: "Duration" },
    { key: "Platform Management", value: "Platform Management" },
    { key: "usuarios", value: "Users" },
    { key: "conductores", value: "Drivers" },
    { key: "pasajeros", value: "Passengers" },
    { key: "vehiculos", value: "Vehicles" },
    { key: "vehiculo", value: "Vehicle" },
    { key: "Correo Electrónico", value: "Email" },
    { key: "viajes", value: "Trips" },
    { key: "Mis vehiculos", value: "My Vehicles" },
    { key: "Actualizado", value: "Updated" },
    { key: "Tu próximo viaje", value: "Your next trip" },
    {
      key: "Gestiona la seguridad de tu cuenta",
      value: "Manage your account security",
    },
    { key: "Actualizar Contraseña", value: "Update Password" },
    { key: "Seguridad", value: "Security" },
    {
      key: "Buscar vehículo por patente o marca...",
      value: "Search vehicle by plate or brand...",
    },
    {
      key: "Buscar viaje por fecha u origen...",
      value: "Search trip by date or origin...",
    },
    {
      key: "Buscar por patente o conductor",
      value: "Search by license plate or driver",
    },
    {
      key: "Buscar usuario por N° documento o nombre...",
      value: "Search user by ID number or name...",
    },
    { key: "Agregar", value: "Add" },
    { key: "Agregar Usuario", value: "Add User" },
    { key: "Agregar Conductor", value: "Add Driver" },
    { key: "Agregar Vehículo", value: "Add Vehicle" },
    { key: "Guardar", value: "Save" },
    { key: "Guardar Cambios", value: "Save Changes" },
    { key: "Activo", value: "Active" },
    { key: "Inactivo", value: "Inactive" },
    { key: "Cancelado", value: "Canceled" },
    { key: "N/A", value: "N/A" },
    { key: "Completado", value: "Completed" },
    { key: "Pendiente", value: "Pending" },
    { key: "Editar", value: "Edit" },
    { key: "id", value: "ID" },
    { key: "Nombre", value: "Name" },
    { key: "DNI", value: "DNI Number" },
    { key: "Editar vehículo", value: "Edit Vehicle" },
    { key: "Editar Viaje", value: "Edit Trip" },
    { key: "Email", value: "Email" },
    { key: "Dirección", value: "Address" },
    { key: "Estado", value: "Status" },
    { key: "Acciones", value: "Actions" },
    { key: "Fecha registro", value: "Registration date" },
    { key: "Patente", value: "Plate" },
    { key: "Marca", value: "Brand" },
    { key: "Modelo", value: "Model" },
    { key: "Año", value: "Year" },
    { key: "Color", value: "Color" },
    { key: "Conductor", value: "Driver" },
    { key: "Fecha", value: "Date" },
    { key: "Origen", value: "Origin" },
    { key: "Destino", value: "Destination" },
    { key: "Pasajero", value: "Passenger" },
    { key: "Importe", value: "Amount" },
    { key: "Resumen", value: "Summary" },
    { key: "Editar", value: "Edit" },
    { key: "Ingrese el conductor", value: "Enter the driver" },
    { key: "Ingrese el año", value: "Enter the year" },
    { key: "Ingrese el color", value: "Enter the color" },
    { key: "Ingrese la patente", value: "Enter the license plate" },
    { key: "Ingrese el modelo", value: "Enter the model" },
    { key: "Ingrese la marca", value: "Enter the brand" },
    { key: "Ingrese su nombre", value: "Enter your name" },
    { key: "Ingrese su DNI", value: "Enter your ID" },
    { key: "Ingrese su correo electrónico", value: "Enter your email" },
    { key: "Ingrese su contraseña", value: "Enter your password" },
    { key: "Masculino", value: "Male" },
    { key: "Femenino", value: "Female" },
    { key: "Otro", value: "Other" },
    { key: "Género", value: "Gender" },
    { key: "Selecciona tu género", value: "Select your gender" },
    { key: "Contraseña Actual", value: "Current Password" },
    { key: "Nueva Contraseña", value: "New Password" },
    { key: "Confirmar Contraseña", value: "Confirm Password" },
    { key: "Información Personal", value: "Personal Information" },
    {
      key: "Actualiza tu información de perfil",
      value: "Update your profile information",
    },
    { key: "Notificaciones", value: "Notifications" },
    {
      key: "Configura cómo quieres recibir notificaciones",
      value: "Configure how you want to receive notifications",
    },
    { key: "Notificaciones Push", value: "Push Notifications" },
    {
      key: "Recibe notificaciones en tu dispositivo",
      value: "Receive notifications on your device",
    },
    { key: "Sonidos", value: "Sounds" },
    {
      key: "Reproduce sonidos para notificaciones importantes",
      value: "Play sounds for important notifications",
    },
    { key: "Correos Electrónicos", value: "Emails" },
    {
      key: "Recibe actualizaciones por correo electrónico",
      value: "Receive updates via email",
    },
    { key: "Privacidad y Seguridad", value: "Privacy and Security" },
    {
      key: "Gestiona la privacidad y seguridad de tu cuenta",
      value: "Manage your account privacy and security",
    },
    {
      key: "Autenticación de dos factores",
      value: "Two-Factor Authentication",
    },
    {
      key: "Añade una capa extra de seguridad a tu cuenta",
      value: "Add an extra layer of security to your account",
    },
    { key: "Compartir datos de ubicación", value: "Share location data" },
    {
      key: "Permite que la app acceda a tu ubicación",
      value: "Allow the app to access your location",
    },
    { key: "Historial de sesiones", value: "Session history" },
    {
      key: "Ver y gestionar tus sesiones activas",
      value: "View and manage your active sessions",
    },
    { key: "Información Legal", value: "Legal Information" },
    {
      key: "Términos y condiciones de uso",
      value: "Terms and Conditions of Use",
    },
    { key: "Términos de Servicio", value: "Terms of Service" },
    { key: "Ver", value: "View" },
    { key: "Política de Privacidad", value: "Privacy Policy" },
    { key: "Licencias de Terceros", value: "Third-Party Licenses" },
    { key: "Cerrar Sesión", value: "Log Out" },
    { key: "Eliminar Cuenta", value: "Delete Account" },
    { key: "Panel del Conductor", value: "Driver Dashboard" },
    { key: "Efectivo", value: "Cash" },
    { key: "Conectado", value: "Online" },
    { key: "Desconectado", value: "Offline" },
    { key: "Recoger en", value: "Pick up at" },
    { key: "Destino", value: "Destination" },
    { key: "Rechazar", value: "Decline" },
    { key: "Aceptar", value: "Accept" },
    { key: "Viaje", value: "Trip" },
    { key: "Ganancias", value: "Earnings" },
    { key: "Distancia", value: "Distance" },
    { key: "Tiempo", value: "Time" },
    { key: "Mensajes", value: "Messages" },
    { key: "Salir", value: "Exit" },
    { key: "Todos", value: "All" },
    { key: "Buscar por dirección o fecha", value: "Search by address or date" },
    { key: "Distancia total", value: "Total distance" },
    { key: "Ingresos totales", value: "Total earnings" },
    { key: "Total de viajes", value: "Total trips" },
    { key: "Ver detalles", value: "View details" },
    { key: "Descargar Reporte", value: "Download Report" },
    { key: "Métodos de Pago Guardados", value: "Saved Payment Methods" },
    {
      key: "Selecciona tu método de pago predeterminado",
      value: "Select your default payment method",
    },
    { key: "Agregar método de pago", value: "Add payment method" },
    { key: "Historial de Pagos", value: "Payment History" },
    { key: "Revisa tus pagos recientes", value: "Review your recent payments" },
    { key: "Ver historial completo", value: "View full history" },
    { key: "Detalles de viaje", value: "Trip Details" },
    { key: "Fecha y Hora", value: "Date and Time" },
    { key: "Ubicaciones", value: "Locations" },
    { key: "Método de Pago", value: "Payment Method" },
  ],
};
